#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Bundle JavaScript files for Yakuniy Imtixon project
Removes ES6 import/export statements and combines all files
"""

import os
import re
from datetime import datetime

def read_file(filepath):
    """Read file with UTF-8 encoding"""
    try:
        with open(filepath, 'r', encoding='utf-8') as f:
            return f.read()
    except Exception as e:
        print(f"❌ Error reading {filepath}: {e}")
        return None

def clean_code(code, filename):
    """Remove import/export statements from code"""
    # Remove import statements
    code = re.sub(r'import\s+.*?from\s+[\'"].*?[\'"];?\s*\r?\n', '', code)
    
    # Remove export keyword but keep the rest
    code = re.sub(r'export\s+', '', code)
    
    return code

def create_bundle():
    """Create bundled JavaScript file"""
    base_dir = os.path.dirname(os.path.abspath(__file__))
    
    # Files to bundle in order
    files = [
        ('data/questions.js', 'Questions Database'),
        ('utils/timer.js', 'Timer Utility'),
        ('utils/storage.js', 'Storage Utility'),
        ('app.js', 'Main Application')
    ]
    
    # Start building bundle
    bundle = f"""// Bundled JavaScript for Yakuniy Imtixon
// Auto-generated on: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}
// DO NOT EDIT THIS FILE DIRECTLY - Edit source files and rebuild

"""
    
    print("🔨 Creating bundle...")
    print("=" * 60)
    
    for filepath, description in files:
        full_path = os.path.join(base_dir, filepath)
        print(f"📄 Processing: {filepath}")
        
        code = read_file(full_path)
        if code is None:
            print(f"⚠️  Skipping {filepath}")
            continue
        
        # Clean the code
        cleaned = clean_code(code, filepath)
        
        # Add to bundle with separator
        bundle += f"\n{'='*60}\n"
        bundle += f"// {description}\n"
        bundle += f"// Source: {filepath}\n"
        bundle += f"{'='*60}\n\n"
        bundle += cleaned
        bundle += "\n"
        
        print(f"   ✅ Added ({len(cleaned)} bytes)")
    
    # Write bundle
    output_path = os.path.join(base_dir, 'app-bundled.js')
    try:
        with open(output_path, 'w', encoding='utf-8') as f:
            f.write(bundle)
        
        file_size = len(bundle)
        print("=" * 60)
        print(f"✅ SUCCESS! Bundle created: app-bundled.js")
        print(f"📦 Total size: {file_size:,} bytes ({file_size/1024:.1f} KB)")
        print(f"📁 Location: {output_path}")
        print("=" * 60)
        return True
        
    except Exception as e:
        print(f"❌ Error writing bundle: {e}")
        return False

if __name__ == '__main__':
    print("\n" + "="*60)
    print("  YAKUNIY IMTIXON - JavaScript Bundler")
    print("="*60 + "\n")
    
    success = create_bundle()
    
    if success:
        print("\n✨ Bundle is ready! Refresh your browser to see changes.\n")
    else:
        print("\n❌ Bundle creation failed. Check errors above.\n")
